language: go

go:
  - 1.8.x

install: cd server && make install-helpers

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
    â€” sh .travis/deploy_dockerhub.sh
    - sh .travis/deploy_heroku.sh
