language: go

go:
  - 1.8.x

install: cd server && make install-helpers

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=lbohdan/chat_academy
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
    - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
    - heroku plugins:install heroku-container-registry
    - docker login -e _ -u _ --password=$HEROKU_API_KEY registry.heroku.com
    - heroku container:push web --app $HEROKU_APP_NAME
